apiVersion: v1
kind: Namespace
metadata:
  name: csi-e2e
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-e2e
subjects:
- kind: ServiceAccount
  name: default # name of your service account
  namespace: csi-e2e # this is the namespace your service account is in
roleRef: # referring to your ClusterRole
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
